### ISSUE TITLE
[MediaTek] Boot partition is read-only problem

### ISSUE THREAD

**Issue by JesusMaxim** [Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver#13]
![IMG_20220513_112958](https://user-images.githubusercontent.com/104729774/168319041-d468ad9b-99e4-47e6-a349-031aba23a0fc.jpg)

I have a problem with version 1.7,in the previous version I had no problem with the module,now it tells me this error so,I hit delete and when it restarted the module ,then I tried to install the module again and the message said all ok,when I restarted the phone it was still the same message of the image,what can I do?

**Comment by JesusMaxim** [comment]
[magisk_install_log_2022-05-13T11:20:59.log](https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/files/8689119/magisk_install_log_2022-05-13T11.20.59.log)

Here is the Magisk log.

Redmi 9C / MIUI 12.0.21
Zygisk,Denylist and Satefynet Fix

**Comment by HuskyDG** [comment]
> [magisk_install_log_2022-05-13T11:20:59.log](https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/files/8689119/magisk_install_log_2022-05-13T11.20.59.log)
> 
> Here is the Magisk log.
> 
> Redmi 9C / MIUI 12.0.21 Zygisk,Denylist and Satefynet Fix

Your boot partition seems to be read-only. Are you using MediaTek devices?

```
- Flashing new boot image
blockdev: /dev/block/mmcblk0p33: Permission denied
! /dev/block/mmcblk0p33 is read only
```

**Comment by JesusMaxim** [comment]
> > [magisk_install_log_2022-05-13T11:20:59.log](https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/files/8689119/magisk_install_log_2022-05-13T11.20.59.log)
> > Here is the Magisk log.
> > Redmi 9C / MIUI 12.0.21 Zygisk,Denylist and Satefynet Fix
> 
> Your boot partition seems to be read-only. Are you using MediaTek devices?
> 
> ```
> - Flashing new boot image
> blockdev: /dev/block/mmcblk0p33: Permission denied
> ! /dev/block/mmcblk0p33 is read only
> ```

Yes

**Comment by JesusMaxim** [comment]
[magisk_log_2022-05-13T12:04:06.log](https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/files/8689275/magisk_log_2022-05-13T12.04.06.log)

there is not only this error mmcblk0p33, there are many more.

**Comment by HuskyDG** [comment]
https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/releases/tag/v1.7_readonly-boot

**Comment by HuskyDG** [comment]
> > becasue Mediatek devices cannot `dd` boot image in live boot, you might need to flash custom boot image from recovery or fastboot
> 
> I'm sorry but I really have no idea how to start doing that, first of all I don't know where to get the Custom boot, and what is the use of the new version that you published

It will import custom boot image to Internal storage so that you can flash it from fastboot or recovery

**Comment by HuskyDG** [comment]
previous version v1.6, the installation doesn't check for successful or fail when flashing boot image

**Comment by HuskyDG** [comment]
sorry, maybe what i said is a bit confusing

**Comment by JesusMaxim** [comment]
![Uploading IMG_20220513_124420.jpg…]()

All good?

**Comment by HuskyDG** [comment]
> ![IMG_20220513_124420](https://user-images.githubusercontent.com/104729774/168331376-e60aa5b6-3c7d-48d1-9806-4e75b2790df2.jpg)
> 
> All good?

yes

**Comment by JesusMaxim** [comment]
> sorry, maybe what i said is a bit confusing

Easy, if I understand, the translator helps me with this quite well haha

**Comment by JesusMaxim** [comment]
> > ![IMG_20220513_124420](https://user-images.githubusercontent.com/104729774/168331376-e60aa5b6-3c7d-48d1-9806-4e75b2790df2.jpg)
> > All good?
> 
> yes

One question, what will happen with the next updates?

Do I have to go through the same process?

**Comment by HuskyDG** [comment]
> > > ![IMG_20220513_124420](https://user-images.githubusercontent.com/104729774/168331376-e60aa5b6-3c7d-48d1-9806-4e75b2790df2.jpg)
> > > All good?
> > 
> > 
> > yes
> 
> One question, what will happen with the next updates?
> 
> Do I have to go through the same process?

This is Mediatek limitation, so the only way is flashing from Recovery or Fastboot

**Comment by JesusMaxim** [comment]
Do I upgrade to 1.7.1 or stay on 1.7 pre-release?

**Comment by HuskyDG** [comment]
> Do I upgrade to 1.7.1 or stay on 1.7 pre-release?

They are the same, just different version, so you can stay

**Comment by Fakhri-Heavenly** [comment]
> sorry, maybe what i said is a bit confusing

I have this issue too, this is my log
[Zenfone 3 ZC553KL bootloop protector log](https://drive.google.com/file/d/1-0QsIVyVQliVh6UMaQNOXXKwk3xeTHOM/view?usp=drivesdk)
