### ISSUE TITLE
I have no ideas for a title 

### ISSUE THREAD

**Issue by JesusMaxim** [Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver#16]
it's me again, I'm sorry but I have a similar problem to the previous one, but this time the module didn't give me the boot to flash it.

Samsung S6 - Android 6.0.1

[magisk_install_log_2022-05-15T11:01:07.log](https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/files/8695255/magisk_install_log_2022-05-15T11.01.07.log)

**Comment by HuskyDG** [comment]
> it's me again, I'm sorry but I have a similar problem to the previous one, but this time the module didn't give me the boot to flash it.
> 
> Samsung S6 - Android 6.0.1
> 
> [magisk_install_log_2022-05-15T11:01:07.log](https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/files/8695255/magisk_install_log_2022-05-15T11.01.07.log)

It only gives boot image if your boot partition can't be modified (read-only).
This device does not have this restriction so module will flash it directly

**Comment by JesusMaxim** [comment]
> > it's me again, I'm sorry but I have a similar problem to the previous one, but this time the module didn't give me the boot to flash it.
> > Samsung S6 - Android 6.0.1
> > [magisk_install_log_2022-05-15T11:01:07.log](https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/files/8695255/magisk_install_log_2022-05-15T11.01.07.log)
> 
> It only gives boot image if your boot partition can't be modified (read-only). This device does not have this restriction so module will flash it directly

ok, so how do I fix this?

![20220515_120103](https://user-images.githubusercontent.com/104729774/168482309-f576335f-0d32-473a-96ab-869a54142f4b.png)
?
