### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by jwgn** [Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver#17]
Ho do I uninstall this? I ran `su -c /data/adb/rm_saver` several times, it repacks the boot image, reboots, seems gone, but it comes back. After some time, after rebooting, after flashing a new Magisk version etc. At some point it just shows up in the Magisk Manager and I am able to run the uninstall script again. But it's not persistent. Please help me remove it.

Pixel 6 on Android 12.1.

**Comment by ameeno** [comment]
Same issue.

**Comment by HuskyDG** [comment]
Flash/restore stock boot image and re-root with Magisk

**Comment by ameeno** [comment]
I want to uninstall. Also I cannot get boot img for my ROM (CRDroid). I initially flashed magisk APK file as a zip via twrp which auto patched my boot image. If I can find a backup magisk made, maybe I can flash that first and then restore.


Maybe your app should like make a backup boot image before it installs patched one?

**Comment by ameeno** [comment]
Do you know where magisk keeps its backups on first install via twrp? Actually. I just realised that I formatted data after installing ROM, gapps magisk (android 12L encryption)

**Comment by jwgn** [comment]
I already downloaded a new factory image, patched the boot.img it with Magisk, removed Magisk, installed the Android Update, then flashed the patched boot.img. Bootloop Protector was uninstalled before, now it is back. Uninstalled it again. Came back. I cannot remove it.

**Comment by Vyer98** [comment]
this module only causes boot failure I warn you don't install this module if you don't need it, I installed version 1.5 & there was no problem, when version 1.7.2 (cwiw) was available I decided to update but when it rebooted & ended up failing to boot continuously

**Comment by jwgn** [comment]
The biggest issue was to install it at all. No problems with it, I just don't need it anymore. Please provide a way to remove it reliably.

**Comment by HuskyDG** [comment]
Try https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/releases/tag/v1.8
