### ISSUE TITLE
Module causes bootloops on >=Magisk v25

### ISSUE THREAD

**Issue by romhacks** [Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver#18]
I suspect this is due to magiskinit being rewritten. Any device with v25 and this module installed will reliably fail to boot until a "clean" magisk boot image is started, and the module is uninstalled.

Device:
Pixel 6
Android 13 Beta 2.1
Magisk v25

**Comment by HuskyDG** [comment]
Can you send dmesg? Since module only uses magisk overlay.d feature, i don't know problems clearly

**Comment by HuskyDG** [comment]
Patching boot image is now optional
https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/releases/tag/v1.8
