### ISSUE TITLE
Script not installed in boot image

### ISSUE THREAD

**Issue by LandChit** [Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver#19]
I have reinstalled the module multiple times
im new to the rooting scene so im not sure what to do

**Comment by HuskyDG** [comment]
Can you give the result of this command:

```
ls $(magisk --path)/.magisk/saver.sh
```

**Comment by LandChit** [comment]
ls: /dev/NprcEF/saver.sh: No such file or directory

**Comment by LandChit** [comment]
i also have a question

> Can you give the result of this command:
> 
> ```
> su -c 'ls $(magisk --path)/saver.sh'
> ```

this is my result
ls: /dev/NprcEF/saver.sh: No such file or directory

**Comment by LandChit** [comment]
i also have a question
if i dont have TWRP or any custom recovery
is it required to have the "new_safemode" file for this module to work

**Comment by HuskyDG** [comment]
Magisk seems to fail to load overlay.d. Can you send the installation logs
and dmesg (can be obtained by `dmesg >/sdcard/dmesg.txt`)?

Vào 16:53, Th 2, 20 thg 6, 2022 LandChit ***@***.***> đã viết:

**Comment by LandChit** [comment]
[dmesg.txt](https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/files/8939689/dmesg.txt)

**Comment by HuskyDG** [comment]
Please send it as file

**Comment by HuskyDG** [comment]
Okey

**Comment by LandChit** [comment]
sorry about that i sent it via email haha

**Comment by HuskyDG** [comment]
Try https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/releases/tag/v1.8

**Comment by LandChit** [comment]
fixed it thanks
