### ISSUE TITLE
Can restore it when the UI and system programs crash?

### ISSUE THREAD

**Issue by SMAAMX** [Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver#2]
In some cases, the Magisk causes the programs to crash and the restart to continue, and this module could not save the system from the boot loop due to the module.
In fact, the boot completes, but after less than a few seconds, it automatically shuts down again due to the use of the wrong graphics card driver module.
> Thank you, this can save a lot of boot loops, but it does not work In some cases And I have no logs of an accident and it is empty

**Comment by HuskyDG** [comment]
> In some cases, the Magisk causes the programs to crash and the restart to continue, and this module could not save the system from the boot loop due to the module. In fact, the boot completes, but after less than a few seconds, it automatically shuts down again due to the use of the wrong graphics card driver module.
> 
> > Thank you, this can save a lot of boot loops, but it does not work In some cases And I have no logs of an accident and it is empty

I'm finding a way to disable all magisk modules from recovery.
Thanks!

**Comment by SMAAMX** [comment]
Thank you very much♥️

**Comment by SMAAMX** [comment]
This is great can save the Android from all boot loops Magisk
I've always been worried about using the module Magisk of the phone boot loop, but with this module you solved my problem♥️♥️♥️🥰.

**Comment by HuskyDG** [comment]
> This is great can save the Android from all boot loops Magisk I've always been worried about using the module Magisk of the phone boot loop, but with this module you solved my problem♥️♥️♥️🥰.

https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/tree/v1.4#disable-from-custom-recovery

**Comment by SMAAMX** [comment]
Thanks I was able to disable the module through custom recovery
