### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by 2286306812** [Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver#23]
Freeze some relatively power-hungry system software, resulting in bootloop, which is not within the scope of the module.
You can consider adding functions in the next version. In the second bootloop, all system software will be automatically thawed to ensure normal operation of memory.

**Comment by HuskyDG** [comment]
You better should use systemless debloat which is also a magisk module instead of disabling system apps.
