### ISSUE TITLE
Should I install systemui bootloop saver as well? 

### ISSUE THREAD

**Issue by Jon8RFC** [Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver#7]
Does your module cover systemui bootloops as similarly to this module:
https://github.com/tsukimio/systemui-bootloop

Should I install it alongside yours, or does yours cover its functionality? Or, does it not cover it, but might cause conflicts in the way it functions...causing a bootloop because of one another, should one module detect a bootloop?

Thanks for this module!

**Comment by HuskyDG** [comment]
Yes

**Comment by Jon8RFC** [comment]
> Yes

Sorry, would you mind clarifying which question that is in response to?

**Comment by HuskyDG** [comment]
>Should I install it alongside yours? 
Yes you can
> does yours cover its functionality? 
No, it doesn't
> Or, does it not cover it, but might cause conflicts in the way it functions...

It will not conflict but i will implement it if you want

> causing a bootloop because of one another, should one module detect a bootloop?

Yes, it should


Bonus: Due to limitations, I cannot make bootloop protector run earlier than other module. And some bootloop can't be prevented.

**Comment by Jon8RFC** [comment]
That'd be great if you could implement that functionality,thanks for offering! I wish I knew how to write it and submit a pull request. I'm just a user.

I really appreciate your module. It has come in handy twice so far when I didn't pay attention to disable a module I knew would create problems.

**Comment by HuskyDG** [comment]
I hope this will help you
https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver/releases/tag/v1.7
