### ISSUE TITLE
Stuck on bootloop even with the module enabled

### ISSUE THREAD

**Issue by RadioactivePlays** [Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver#9]
I got stuck on bootloop 3 times already lol 😅, that occurs specifically when i try to flash Audio Headquarter Magisk module (https://github.com/Alcatraz323/audiohq_module). Any tios on it?

**Comment by HuskyDG** [comment]
https://github.com/Magisk-Modules-Alt-Repo/HuskyDG_BootloopSaver#disable-from-custom-recovery
